version: 0.2

phases:
  install:
    commands:
      - make init
  pre_build:
    commands:
      - make test
  build:
    commands:
      - make build
  post_build:
    commands:
      - make push
      - printf '[{"name":"drupal9-php","imageUri":"303536629688.dkr.ecr.ap-southeast-2.amazonaws.com/drupal9:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
