version: 0.2
env:
  variables:
    DOCKER_REPO: "303536629688.dkr.ecr.ap-southeast-2.amazonaws.com/drupal9"
phases:
  install:
    commands:
      - make init
  pre_build:
    commands:
      - make test
  build:
    commands:
      - make build
  post_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $DOCKER_REPO
      - docker tag drupal9:latest $DOCKER_REPO:latest
      - docker push $DOCKER_REPO:latest
      - printf '[{"name":"drupal9-php","imageUri":$DOCKER_REPO:latest}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
